@startuml
'https://plantuml.com/state-diagram

participant ユーザー
participant マイクラサーバー管理用サーバー
participant マイクラサーバー
participant 専用プラグイン

マイクラサーバー管理用サーバー -> マイクラサーバー管理用サーバー : 起動

ユーザー -> マイクラサーバー管理用サーバー : 接続

マイクラサーバー管理用サーバー -> マイクラサーバー : 起動
マイクラサーバー -> マイクラサーバー管理用サーバー : 標準入出力

マイクラサーバー -> 専用プラグイン : 起動
専用プラグイン -> マイクラサーバー管理用サーバー : 接続

ユーザー -> マイクラサーバー管理用サーバー : コマンド送信
マイクラサーバー管理用サーバー -> ユーザー : コンソールの文字列送信

@enduml